version: '3.8'

services:
  postgres:
    container_name: postgres-article
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_intership
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4-article
    image: dpage/pgadmin4:8.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8888:80"
    depends_on:
      - postgres
    
    
